### PR TITLE
Play send sound setting for iOS

### PR DESCRIPTION
**Pull request by jakeump**
* Option to play send sound if theme is iOS
* Default iMessage sound plays on send if enabled
* #524

### CODE REVIEW

**Comment by tneotia** [comment]
See my comments in discord #community-contributions

**Comment by zlshames** [comment]
As well as mine. Thank you for the PR and work, I just think we can't provide the same assets that Apple uses for legal reasons. An alternative could be that we allow users to choose a custom mp3 to use. As well as have a few presets that are royalty free

**Review by jakeump — COMMENTED** [review]
updated

**Comment by tneotia** [comment]
Since this includes UI changes in settings, can you rebase off of tanay/bordeaux/widget-rewrites and target feature/widget-rewrites in your PR? Just to avoid a lot of merge conflicts. Sorry for the change!

**Pull request closed without merging**
