### PR TITLE
Monet color theming

### PR DESCRIPTION
**Pull request by elliotnash**
Add support to source bluebubbles' colors from monet colors (Material You dynamic colors) on supported devices running Android 12+

### CODE REVIEW

**Comment by zlshames** [comment]
Hey.... what's monet color theming

**Comment by elliotnash** [comment]
sorry about that lol, it's the name for Material You's theming engine for Android 12 that generates colors based on your wallpaper (and can also be manually set).

**Comment by zlshames** [comment]
Awesome. This won't go into 1.8.0, but will look at it for after that. Can we change the PR to be into development please?

**Comment by elliotnash** [comment]
sounds good :)

**Comment by zlshames** [comment]
Hey @elliotnash do you think you could look into merging the master changes into this branch so there are no merge conflicts?

**Pull request closed without merging**
