### PR TITLE
Play Send Sound Setting

### PR DESCRIPTION
**Pull request by jakeump**
* Custom send and receive sound on mobile and web
* https://github.com/BlueBubblesApp/bluebubbles-app/issues/524

Due to some issues with Git, this took a while to get right.

### CODE REVIEW

**Comment by tneotia** [comment]
Did you add the default iMessage sound? I don't see it in the assets in your PR

**Comment by jjoelj** [comment]
Also, file paths for app data should use the application support directory on desktop.

**Comment by jakeump** [comment]
@tneotia I had originally done that, but was told it's not a good idea due to copyright. Thus, I have only enabled custom sounds–no defaults.

I will look into how to use the application support directory

**Comment by tneotia** [comment]
Sounds good, your OP had said plays default sound so I was just curious

**Comment by jakeump** [comment]
> Sounds good, your OP had said plays default sound so I was just curious

Oh yeah that was just copy-pasted from my original PR and I didn't bother to read it 🤦‍♂️

**Comment by zlshames** [comment]
@jakeump so is this good to go? probably can get it into our v1.11.0 release

**Comment by zlshames** [comment]
@jakeump just checking back in on this. Let me know what the status of this is. Thanks!

**Comment by jakeump** [comment]
> @jakeump just checking back in on this. Let me know what the status of this is. Thanks!

Hey Zach, sorry I've been putting this off a bit. I've been really busy with school and interviews recently. I'll try to get this finished by next weekend

**Comment by zlshames** [comment]
> > @jakeump just checking back in on this. Let me know what the status of this is. Thanks!
> 
> Hey Zach, sorry I've been putting this off a bit. I've been really busy with school and interviews recently. I'll try to get this finished by next weekend

Hey, no real rush on this. Take it at your own pace. I was just pinging because I didn't get a response from you from my last message

**Comment by tneotia** [comment]
Hi @jakeump I went ahead and cherry-picked and updated your commit, this should make its way into v1.11 Beta 3. You should still get credit for it, GitHub shows as co-authored. Thanks for this!

**Comment by jakeump** [comment]
> Hi @jakeump I went ahead and cherry-picked and updated your commit, this should make its way into v1.11 Beta 3. You should still get credit for it, GitHub shows as co-authored. Thanks for this!

Hey I'm sorry I couldn't get this done, school has been pretty time-consuming and I didn't have flutter setup on my laptop. Appreciate you picking up my slack

**Pull request closed without merging**
