### PR TITLE
Backup naming bug fixes

### PR DESCRIPTION
**Pull request by SoPat712**

### CODE REVIEW

**Comment by tneotia** [comment]
@SoPat712 are you gonna do the todo in this commit in this same PR? Or should I merge

**Comment by SoPat712** [comment]
Sorry. I haven't gotten around to it. I'll do it, don't merge yet.

**Comment by SoPat712** [comment]
Wait I did do it

**Comment by SoPat712** [comment]
I just forgot to remove the Todo

**Pull request merged**
