### PR TITLE
Check for server updates on app cold start

### LINKED ISSUE #1987: Auto check for server updates every so often & notify user
Do this when the app starts fresh. On a delay so it doesn't hold up the UI and cause lag. Only do it at max 1 time every 6 hours. Add a toggle to turn off reminders for it if users want to ignore them

### PR DESCRIPTION
**Pull request by tneotia**
Closes #1987

### CODE REVIEW

**Comment by zlshames** [comment]
Looks good, but please make this on a 15 second delay as to not interfere with startup code such as initiating the DB store or startup time.

**Review by zlshames — CHANGES_REQUESTED** [review]
Add delay

**Comment by tneotia** [comment]
This doesn't actually interfere with startup code, the API call isn't `await`ed so other code is free to run after it.

**Comment by tneotia** [comment]
I dunno if its really going to cause lag tbh, its just a network call and doesn't update the UI at all. There isn't any sort of heavy "processing" to it. I can shift the API call over to an isolate if you want, though (but the actual rendering of the dialog will need to be done on the main thread)

**Comment by zlshames** [comment]
> I dunno if its really going to cause lag tbh, its just a network call and doesn't update the UI at all. There isn't any sort of heavy "processing" to it. I can shift the API call over to an isolate if you want, though (but the actual rendering of the dialog will need to be done on the main thread)

How is this shown when you do the following:
1. Tap through a notification
2. App opens and update dialog shows
3. Navigator transitions to the chat opened via the notification

Will there be any issues with navigation/the back button?

**Comment by zlshames** [comment]
> No I dont think so, it just depends which "route" is pushed on the stack first. If it takes a while for the app to open the message page, itll probably open the dialog first, then the message page on top of it. When the user presses back, itll take them back to the convo screen but the dialog will be popped open. Then they hit "OK" to close it.

ok that's fine

**Pull request merged**
