### PR TITLE
Change how the Start Chat button animation works

### PR DESCRIPTION
**Pull request by SoPat712**

### CODE REVIEW

**Review by zlshames — COMMENTED** [review]
Do you have a demo of it with the changes?

**Comment by SoPat712** [comment]
Adding it rn

**Comment by SoPat712** [comment]
https://file.io/q50nzYm7vtUZ

**Comment by SoPat712** [comment]
Oh also changed the color of the button. It was too dark in light mode and too bright in dark mode.

**Comment by zlshames** [comment]
> https://file.io/q50nzYm7vtUZ

can you upload this to a streaming platform. I don't like to download files off the internet like this

**Comment by tneotia** [comment]
You can upload videos directly into github if you use the browser version just FYI

**Comment by SoPat712** [comment]
It's too big, Github has a 10MB limit, and samsung screen records in full res for some stupid reason. i'll zip it and try again

**Comment by SoPat712** [comment]
https://user-images.githubusercontent.com/30350506/143070327-daa9e67e-3aa1-421b-bb03-a8fbc616dbac.mp4

**Comment by SoPat712** [comment]
It changes by distance from scroll Start position, instead of just changing as soon as you scroll a direction.

**Comment by zlshames** [comment]
> It changes by distance from scroll Start position, instead of just changing as soon as you scroll a direction.

What's with the shadow under the Messages header

**Comment by SoPat712** [comment]
tanay did that, not me

**Comment by SoPat712** [comment]
¯\_(ツ)_/¯ sorry Tanay gotta throw you under the bus

**Comment by zlshames** [comment]
@tneotia whatever is going on with the messages header, we should fix before merging

**Comment by SoPat712** [comment]
Oh yeah he just did a thing with the gradient. I'll fix that right now

**Comment by tneotia** [comment]
> What's with the shadow under the Messages header

@zlshames I was trying to do a clever thing where the chat tiles would appear to go behind the search bar on the bottom, but I couldn't make the search bar fully transparent because otherwise the chat tiles would appear in the notification area as well. So I used a gradient from the scaffold background color at the top (to prevent chat tiles being shown at the top) to transparent at the bottom (so chat tiles can appear to go behind the search bar on the bottom). It looks good in dark mode but I guess in light mode the transparent doesn't work for whatever reason. I'm guessing its because the original background color of the app is black, so we need to somehow change that.

**Comment by SoPat712** [comment]
i'll do what google does. color the status bar and make the appbar transparent

**Comment by tneotia** [comment]
I fixed the appbar coloring, merging

**Comment by SoPat712** [comment]
> 

 👍

**Pull request merged**
